input = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............""".splitlines()
input = open("2025/inputs/07.txt").readlines()
G = [list(r) for r in input]
R = len(G)
C = len(G[0])

for r in range(R):
    for c in range(C):
        if G[r][c] == "S":
            G[r][c] = "|"
            break

splits = 0
for r in range(R - 1):
    for c in range(C):
        if G[r][c] == "|":
            if G[r + 1][c] == ".":
                G[r + 1][c] = "|"
            elif G[r + 1][c] == "^":
                G[r + 1][c - 1] = "|"
                G[r + 1][c + 1] = "|"
                splits += 1

print(splits)
